### ISSUE TITLE
Uncaught Exception: Invalid status code.

### ISSUE THREAD

**Issue by tazfrison** [demostf/api#1]
When uploading a demo, received the following response from the server:

```<br />
<b>Fatal error</b>:  Uncaught Exception: Invalid status code. in /app/vendor/mikecao/flight/flight/net/Response.php:127
Stack trace:
#0 /app/src/upload.php(36): flight\net\Response-&gt;status(2)
#1 /app/vendor/mikecao/flight/flight/core/Dispatcher.php(169): Demostf\API\{closure}(Object(ErrorException))
#2 /app/vendor/mikecao/flight/flight/core/Dispatcher.php(145): flight\core\Dispatcher::callFunction(Object(Closure), Array)
#3 /app/vendor/mikecao/flight/flight/core/Dispatcher.php(49): flight\core\Dispatcher::execute(Object(Closure), Array)
#4 /app/vendor/mikecao/flight/flight/Engine.php(92): flight\core\Dispatcher-&gt;run('error', Array)
#5 /app/vendor/mikecao/flight/flight/Engine.php(185): flight\Engine-&gt;__call('error', Array)
#6 [internal function]: flight\Engine-&gt;handleException(Object(ErrorException))
#7 {main}
  thrown in <b>/app/vendor/mikecao/flight/flight/net/Response.php</b> on line <b>127</b><br />
```

Relevant files:
https://github.com/demostf/api/blob/master/src/upload.php
https://github.com/mikecao/flight/blob/v1.3.8/flight/net/Response.php

Seems like the code retrieved by `$ex->getCode()` doesn't exist in flight's list of status codes.  Can't tell what the code is or what error generated it.

It looks like the codes list on Response is public, so you should be able to use `array_key_exists($code, Response::$codes)` to sanitize the code before line 36 of Upload.php.

Demo used can be downloaded from https://drive.google.com/file/d/18roZ72-H1OLKcOkx6OkTzglwxMgQenfe/view?usp=sharing

**Comment by icewind1991** [comment]
should be fixed with b06cf67a704dd44dfac7190c74c5f0cf4784f77d
